Jenkinsfile, useful-notes.md
The library should load the current sha1 for it's CI
=> The library should load the current sha1 for it's CI

vars/withKubicEnvironment.groovy
Always run the cleanup/teardown stages.
=> Always run cleanup/teardown stages

vars/createEnvironment.groovy
It shows up horribly in the pipeline UI
=> Avoid waitUntil

src/com/suse/kubic/Environment.groovy, src/com/suse/kubic/Minion.groovy, vars/bootstrapEnvironment.groovy, vars/coreKubicProjectCi.groovy, vars/createEnvironment.groovy
Use the terraform generated environment.json file rather than building our own in CI.
Depends-On: https://github.com/kubic-project/terraform/pull/90
=> Use the TF generated env.json

vars/createEnvironment.groovy
Wget downloads were not showing any progress, this should give us
some idea of whats happening :)
=> Attempt to show some wget progress

vars/bootstrapEnvironment.groovy, vars/cloneAllKubicRepos.groovy
This is still a WIP to test, and uses a stripped down e2e-tests repo in my fork (also WIP) https://github.com/kubic-project/e2e-tests/compare/master...MaximilianMeister:stripdown?expand=1
=> use a stripped down version of the e2e-tests to bootstrap caasp

vars/bootstrapEnvironment.groovy
https://github.com/kubic-project/automation/pull/12
=> save junint xml output in the workspace

vars/coreKubicProjectCi.groovy
This seems to cause the BO UI to render a little weird
during this stage.
=> Remove redundant parallel

vars/bootstrapEnvironment.groovy
~~https://github.com/kubic-project/automation/pull/23~~
=> archive screenshots

Jenkinsfile, vars/coreKubicProjectCi.groovy, vars/githubCollaboratorCheck.groovy
GitHub's org member API doesn't appear to behave as documented,
lets try using the repo collaborator API.
=> Rework GH collaborator check

vars/cleanupEnvironment.groovy, vars/cleanupEnvironmentDevenv.groovy, vars/coreKubicProjectCi.groovy, vars/coreKubicProjectPeriodic.groovy, vars/createEnvironment.groovy, vars/createEnvironmentDevenv.groovy, vars/withKubicEnvironment.groovy
Allow for alternative environment types, and multiple masters
=> Allow for alternative environment types, and multiple masters

vars/cloneAllKubicRepos.groovy, vars/createEnvironmentDevenv.groovy, vars/runTestInfra.groovy
Depends-On: https://github.com/kubic-project/automation/pull/53
=> Testinfra has moved to the automation repo

vars/bootstrapEnvironment.groovy
https://github.com/kubic-project/automation/pull/52
=> archive kubeconfig

src/com/suse/kubic/Addresses.groovy, src/com/suse/kubic/Minion.groovy, vars/createEnvironmentDevenv.groovy, vars/runTestInfra.groovy, vars/scpFromMinion.groovy, vars/shOnMinion.groovy
This is done by using the generated SSH config
=> Handle split public/private IPv4 addresses

vars/cleanupEnvironmentOpenstack.groovy, vars/coreKubicProjectPeriodic.groovy, vars/createEnvironment.groovy, vars/createEnvironmentOpenstack.groovy, vars/withKubicEnvironment.groovy
This PR, once complete, allows for CI to boot a OpenStack based deployment of CaaSP
=> Add an OpenStack Environment Type

vars/gatherKubicLogs.groovy
Gathing logs is one of the more time consuming steps, by doing this
in parallel, this stage should complete faster.
=> Gather logs from all minions in parallel

src/com/suse/kubic/Environment.groovy, vars/createEnvironmentCaaspKvm.groovy, vars/createEnvironmentOpenstack.groovy
This removes a bunch of duplicated code
=> Centralize the env JSON reading

vars/runTestInfra.groovy
With larger numbers of workers, this should perform better than
doing each role in parallel - which puts all the workers into
one basket
=> Run testinfra against each host in parallel

vars/cleanupEnvironmentCaaspKvm.groovy, vars/createEnvironmentCaaspKvm.groovy
Relates to https://github.com/kubic-project/automation/pull/119
=> Pass HTTP Proxy to caasp-kvm

vars/cleanupEnvironment.groovy, vars/cleanupEnvironmentCaaspBareMetal.groovy, vars/createEnvironment.groovy, vars/createEnvironmentCaaspBareMetal.groovy, vars/createEnvironmentWorkers.groovy, vars/createEnvironmentWorkersCaaspBareMetal.groovy
=> Add bare metal deployment

src/com/suse/kubic/OpenstackTypeOptions.groovy, vars/cleanupEnvironment.groovy, vars/coreKubicProjectPeriodic.groovy, vars/createEnvironment.groovy, vars/createEnvironmentOpenstack.groovy, vars/createEnvironmentWorkers.groovy, vars/withKubicEnvironment.groovy
Allow for env types to pass arbitrary options
=> Allow for env types to pass arbitrary options

vars/coreKubicProjectPeriodic.groovy, vars/withKubicEnvironment.groovy
This is useful for when you use Jenkins to build an env, but want
to keep it around for debugging.
=> Make environment destruction optional

vars/bootstrapEnvironment.groovy
To be refactored into a function later on.
=> Fetch caasp-cli and set up Kubernetes login

vars/createEnvironmentCaaspBareMetal.groovy
=> Bare metal: fetch new ISO

src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/coreKubicProjectPeriodic.groovy, vars/createEnvironment.groovy, vars/createEnvironmentCaaspKvm.groovy, vars/createEnvironmentOpenstack.groovy, vars/withKubicEnvironment.groovy
=> [2.0] KVM: Set all machines to 4GB and 4vCPU

vars/cloneAllKubicRepos.groovy, vars/cloneKubicRepo.groovy, vars/withKubicEnvironment.groovy
This will be useful for upgrade testing where we need to clone the "old" code first, deploy it, then move to the new code.
=> Allow for ignoring PRs when cloning in CI

vars/withKubicEnvironment.groovy
Insert the result of every build into a MariaDB instance.
=> Insert build log to local database

vars/coreKubicProjectCi.groovy, vars/coreKubicProjectPeriodic.groovy
This is the workaround a breaking issue that has broken CI for     several days. This should be reverted on Monday.
=> Set CI to use 1 master, 2 workers temporarily

vars/coreKubicProjectCi.groovy, vars/coreKubicProjectTests.groovy, vars/createPod.groovy, vars/withKubicEnvironment.groovy
Depends-On: https://github.com/kubic-project/automation/pull/128
=> Add pod scaling stages

vars/createEnvironmentCaaspBareMetal.groovy
To be used to test etcd leader election with odd/even worker count
=> Pass master and worker count to bare metal deployer

Jenkinsfile
Backport from master branch , commit  c97233379c155ed413d86ba8d4d975e997518649
=> Fix self-CI of Jenkins Lib PRs

vars/gatherKubicLogs.groovy
Ignore tarballs that do not contain a salt events logfile
=> Extract Salt events from supportconfig tarballs

vars/cloneKubicRepo.groovy
Reverts kubic-project/jenkins-library#122
=> Revert "Rebase PRs prior to testing"

vars/bootstrapEnvironment.groovy, vars/configureEnvironment.groovy
Replace the environment variable with the new flag
=> Use Velum Bootstrap --environment flag

vars/coreKubicProjectCi.groovy, vars/coreKubicProjectTests.groovy, vars/runK8SPodTests.groovy, vars/shOnMinion.groovy, vars/upgradeEnvironment.groovy
This does not actually test an upgrade, however, it does test that the upgrade
orchestration can run successfully, without having any actual updates.
=> PR CI: Test 'upgrades'

vars/bootstrapEnvironment.groovy, vars/coreKubicProjectTests.groovy, vars/helmDeleteRelease.groovy, vars/helmInstallChart.groovy, vars/helmInstallClient.groovy
Deploy the MariaDB helm chart as part of CI.
Depends-On: https://github.com/kubic-project/automation/pull/249
=>  Deploy a Helm chart as part of CI

vars/createEnvironmentCaaspBareMetal.groovy, vars/createEnvironmentWorkersCaaspBareMetal.groovy
Backport of #129 from master,
commit 48aa7735582279fc88c3a76fe690f05380419a0c
=> Pass --logsdir to bare metal deployer

vars/createEnvironmentCaaspKvm.groovy
using caasp-kvm flag from https://github.com/kubic-project/automation/pull/262
=> Temporarily disable meltdown/spectre fixes

vars/createEnvironmentCaaspKvm.groovy
This allows for debugging changes to the template more easily
=> KVM: Archive the generated cluster.tf file

vars/addNode.groovy, vars/removeNode.groovy, vars/updateEnvironmentCaaspKvm.groovy
=> enable add/remove node test

vars/cloneKubicRepo.groovy
Reverts kubic-project/jenkins-library#152
=> Revert "Ci auto rebase"

vars/cloneKubicRepo.groovy
I made some fixes to https://github.com/kubic-project/jenkins-library/pull/152 and updated my test environment. Here's some screenshots of passing and failing PRs.
=> Auto rebase PRs prior to testing

vars/createEnvironmentCaaspKvm.groovy, vars/updateEnvironmentCaaspKvm.groovy
this might be helpful for debugging
=> archive terraform state

vars/createEnvironmentCaaspKvm.groovy, vars/updateEnvironmentCaaspKvm.groovy
otherwise nothing will be archived
=> use /logs subpath

vars/updateEnvironmentCaaspKvm.groovy
to compare what has changed after create deployment that makes
terraform create all vm's from scratch again
=> save artifact before the deployment update

src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/createEnvironmentCaaspKvm.groovy, vars/updateEnvironmentCaaspKvm.groovy
=> enable optional meltdown/spectre fixes

Jenkinsfile.housekeeping, vars/coreKubicProjectHousekeeping.groovy
=> Backport Housekeeping Job

vars/bootstrapEnvironment.groovy, vars/configureEnvironment.groovy, vars/coreKubicProjectPeriodic.groovy, vars/coreKubicProjectTests.groovy, vars/withKubicEnvironment.groovy
Related to https://github.com/kubic-project/automation/pull/401
This also moves --enable-tiller from the deployment step to the (earlier) configuration step.
=> Test cri-o

vars/withKubicEnvironment.groovy
http://jenkins.caasp.suse.net/blue/organizations/jenkins/salt.integration/detail/PR-621/7/pipeline
=> don't fail when logs dir already exists

vars/runTestK8sConformance.groovy
=> timeout after 3 hours, not 5 days

.gitignore, Jenkinsfile.codenarc
Relates to https://github.com/kubic-project/automation/pull/459
=> Add codenarc to jenkins-library - Static Analysis for Groovy

vars/bootstrapEnvironment.groovy, vars/upgradeEnvironmentStage1.groovy, vars/upgradeEnvironmentStage2.groovy
=> [Backport of PR 216] Stop parallel ssh in the finally block

vars/withKubicEnvironment.groovy
=> Detect and remove tainted workers

src/com/suse/kubic/CaaspHypervTypeOptions.groovy, vars/cleanupEnvironment.groovy, vars/cleanupEnvironmentCaaspHyperv.groovy, vars/createEnvironment.groovy, vars/createEnvironmentCaaspHyperv.groovy, vars/createEnvironmentWorkers.groovy, vars/prepareImage.groovy, vars/prepareImageCaaspHyperv.groovy, vars/qaCaaspCi.groovy, vars/withKubicEnvironment.groovy
This what we need to support Hyper-V testing.
We still have to discuss about the notifications and where to store the logs in a database so we won't need withQaCaaspEnvironment.groovy which is similar to withQaCaaspEnvironment.groovy
=> add hyperv support for CI

vars/coreKubicProjectClusterTests.groovy
Backport of https://github.com/kubic-project/jenkins-library/pull/258
=> [3.0] Run node tests once

src/com/suse/kubic/Environment.groovy, src/com/suse/kubic/Minion.groovy, vars/runTestInfra.groovy
(cherry picked from commit 8eed4088b925b243bc018de37bb24416a557d951)
=> [3.0] Pass minion status to Test Infra as part of tox env name

Jenkinsfile.codenarc, vars/cloneKubicRepo.groovy, vars/coreKubicProjectCi.groovy, vars/coreKubicProjectHousekeeping.groovy, vars/coreKubicProjectPeriodic.groovy, vars/getRepoInfo.groovy, vars/withKubicEnvironment.groovy
Each repository may use a different token so we should stop hardcoding this in the code and add it to the
repository table instead.
=> Add token information to repository table

Jenkinsfile.codenarc, vars/cloneKubicRepo.groovy, vars/coreKubicProjectCi.groovy, vars/coreKubicProjectHousekeeping.groovy, vars/getRepoInfo.groovy, vars/githubCollaboratorCheck.groovy
Development and release branches may not live in the same repository so make this configurable on the table.
=> Add branch information to the repo table and convert to a Map

vars/cloneKubicRepo.groovy, vars/getRepoInfo.groovy
Add information about the repository itself to the Map.
=> getRepoInfo: Add information about repository name

src/com/suse/kubic/CaaspVMwareTypeOptions.groovy, vars/cleanupEnvironment.groovy, vars/cleanupEnvironmentCaaspVMware.groovy, vars/createEnvironment.groovy, vars/createEnvironmentCaaspVMware.groovy, vars/createEnvironmentWorkers.groovy, vars/prepareImage.groovy, vars/prepareImageCaaspVMware.groovy, vars/withKubicEnvironment.groovy
Initial version, to be merged with https://github.com/kubic-project/automation/pull/608
=> Add VMware support
