kubic-project/jenkins-library

README.md, vars/coreKubicProjectPeriodic.groovy
This allows for multiple different periodic jobs that perform different
tasks. (e.g. variations of nightly upgrade CI jobs etc)
=> Allow periodic jobs to specify a closure

vars/createEnvironment.groovy
Devenv had a smaller timeout (30 min) than the 60 min timeout
for the whole stage. Remove the smaller timeout and allow the
outer timeout to take precedence.
The proper fix here is to add a local cache of the docker
images near the CI workers, preventing the lengthly container
image download. However, this will do for now, as timeouts in
CI are less to do with enforcing performance goals, and are
instead about making sure a CI job does not consume a CI
worker forever.
=> Increase devenv timeout to 60 mins

vars/createEnvironment.groovy
For both the qcow2, and docker images, we should be using the Devel
images, rather than the release images.
=> Ensure we use the devel images for CI

vars/githubCollaboratorCheck.groovy, vars/withKubicEnvironment.groovy
Several of the $class statements we used already have pipeline
variants, without the need to construct by hand. Replace these
with the matching pipeline versions.
=> Replace tasks with pipeline variants

vars/coreKubicProjectPeriodic.groovy, vars/withKubicEnvironment.groovy
Some periodic jobs (e.g. the OpenStack ones) don't need a large node, so
we should allow them to not ask for a large node.
=> Allow periodic jobs to choose their node label

vars/bootstrapEnvironment.groovy
With two new specs added to velum-bootstrap which we don't want to always run, we've added a script to velum-bootstrap to make selection easier.
This updates CI to use the script.
Depends-On: https://github.com/kubic-project/automation/pull/102
=> Avoid velum update specs

vars/coreKubicProjectCi.groovy
This is called from each projects Jenkinsfile, that file in each of the other repos
should *never* differ, they defer everything to this function, so each project is
tested in exactly the same way. This prevents 1 projects config from passing a change
that would otherwise fail with another projects config - i.e. prevents wedgeing CI.
=> coreKubicProjectCi shouldn't accept params

vars/configureEnvironment.groovy, vars/createEnvironmentWorkers.groovy, vars/withKubicEnvironment.groovy
Bare metal environments need to have the admin node created first, so that
the AutoYaST file is being served before creating the workers. This refactor
allows for that
=> Refactor to allow bare metal environments

vars/cleanupEnvironmentCaaspKvm.groovy, vars/withKubicEnvironment.groovy
This is only needed for KVM environments, where the leftover libvirt
resources will cause the next run to fail.
=> Removing a slave on failure to cleanup is KVM only

vars/createEnvironmentCaaspKvm.groovy
When creating a KVM environment, downloading the qcow can sometimes
be really slow, for now, increase this timeout.
=> KVM Increase create env timeout

src/com/suse/kubic/CaaspBareMetalTypeOptions.groovy, src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/createEnvironmentCaaspBareMetal.groovy, vars/createEnvironmentOpenstack.groovy, vars/prepareImage.groovy, vars/prepareImageCaaspBareMetal.groovy, vars/prepareImageCaaspKvm.groovy, vars/prepareImageOpenStack.groovy, vars/withKubicEnvironment.groovy
The current code has been moved to prepareImage, there is still a TODO against
both openstack and bare metal, but these should be handled separately.
This allows for more easily seeing the timings for the build step, without the large
variance introduced by fetching a new image.
=> Split image download into its own step

src/com/suse/kubic/CaaspBareMetalTypeOptions.groovy, src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/createEnvironmentCaaspBareMetal.groovy, vars/createEnvironmentOpenstack.groovy, vars/prepareImage.groovy, vars/prepareImageCaaspBareMetal.groovy, vars/prepareImageCaaspKvm.groovy, vars/prepareImageOpenStack.groovy, vars/withKubicEnvironment.groovy
The current code has been moved to prepareImage, there is still a TODO against
both openstack and bare metal, but these should be handled separately.
This allows for more easily seeing the timings for the build step, without the large
variance introduced by fetching a new image.
Backport of https://github.com/kubic-project/jenkins-library/pull/96
=> [2.0] Split image download into it's own step

vars/coreKubicProjectCi.groovy, vars/coreKubicProjectPeriodic.groovy
This reverts commit b64ae61c05d9a1f3a12daa5c9f9e5abbdafd00c3.
Depends on: https://github.com/kubic-project/velum/pull/387
Depends on: https://github.com/kubic-project/salt/pull/314
Depends on: https://github.com/kubic-project/caasp-container-manifests/pull/134
=> Revert "Set CI to use 1 master, 2 workers temporarily"

src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/prepareImageCaaspKvm.groovy
This allows for jobs to override the channel from devel -> release
using the CaaspKvmTypeOptions object.
=> KVM: Don't hardcode the channel name to devel

vars/gatherKubicLogs.groovy
Ignore tarballs that do not contain a salt events logfile
Backport of https://github.com/kubic-project/jenkins-library/pull/116
=> [2.0] Extract Salt events from supportconfig tarballs

src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/createEnvironmentCaaspKvm.groovy
This will be used by the nightlys to NOT inject code into the caasp-kvm environment.
=> KVM: Add support for vanilla flag

vars/cloneKubicRepo.groovy
Rather than forcing every PR to be manually rebased when a breaking
change lands, CI should just do it.
=> Rebase PRs prior to testing

vars/createEnvironmentCaaspKvm.groovy, vars/prepareImageCaaspKvm.groovy
This is not an ideal change, as we no longer separate the image pull from the
rebuild. Given how slow the Provo connection to Nue can be, this may become
a problem.
For now, lets give it a shot so the Build Service team can revert the temporary
change they have applied for us.
=> Use Velum image from registry.suse.de

vars/runTestK8sConformance.groovy
Depends on: https://github.com/kubic-project/automation/pull/272
=> Remove unused argument `--no-tty` from the conformance tests call

vars/coreKubicProjectTests.groovy, vars/helmInstallChart.groovy, vars/helmInstallClient.groovy, vars/helmTestRelease.groovy
Helm 2.8.2 fixes an issue with --wait, among other compatibility fixes,
allowing us to now use the `helm test` command.
=> Upgrade to Helm 2.8.2 + Add Helm Test step

vars/helmDeleteRelease.groovy, vars/helmTestRelease.groovy
Cleaning up test pods means we destroy the logs we need to gather in order
to debug.
=> Helm Tests: Don't cleanup test pods by default

vars/addNode.groovy, vars/bootstrapEnvironment.groovy, vars/coreKubicProjectPeriodic.groovy, vars/removeNode.groovy, vars/withKubicEnvironment.groovy
Now that the environment is mutable, we need to ensure we re-read the
updated environment.json file, as well as return the environment through
any closures that may modify the environment.
=> Ensure we correctly handle the now mutable environment object

vars/netdataCaptureCharts.groovy, vars/withKubicEnvironment.groovy
Install Netdata on the admin node.
At the end of the run, gather metrics and badges, generate charts and HTML pages and store them as browsable artifacts.
=> Install Netdata, gather metrics

src/com/suse/kubic/CaaspKvmTypeOptions.groovy, vars/createEnvironmentCaaspKvm.groovy
specifically in the sandbox job, which is triggered manually on demand
the download of the image, which is not cached can take much longer than
45min
=> make caaspkvm timeout configurable

vars/gatherKubicLogs.groovy
Updated the gatherKubicLogs step to pull the newly created velum-salt-events-summary.txt and velum-salt-events.yml files directly from the tbz files generated from supportconfig.
No longer running supportutils-parser on the velum-salt-events.yml because the summary file already contains preprocessed clean output.
The new summary is placed in the same file that supportutils-parser wrote previously, [tbz_filename].salt_failures.txt
The full detail in JSON format is placed in [tbz_filename].salt_failures_full.yml
=> During gatherKubicLogs pull salt events directly

vars/upgradeEnvironment.groovy
When upgrading from 2.x to 3.x, we've bumped the version of Dex we include. This update renders all "old" kubeconfig files invalid, and users must re-download updated kubeconfig.
By redownloading the kubeconfig file, we'll allow the 2.x -> 3.x upgrade CI jobs to proceed further.
=> Redownload kubeconfig after upgrade jobs

vars/gatherKubicLogs.groovy
Without --wildcards, the events would not be extracted. Additionally,
simplify the extraction commands and prevent the creation of unnecessary
events files for tarballs which don't contain the salt events.
=> Fix salt event extraction

vars/coreKubicProjectCi.groovy, vars/upgradeEnvironmentStage1.groovy, vars/upgradeEnvironmentStage2.groovy
This allows for upgrade tests to change the automation branch after
it has updated the admin node. This is needed older automation tools
may not be compatible with the newer velum etc.
=> Split upgradeEnvironment into 2 stages

vars/coreKubicProjectPeriodic.groovy
This worker type has significantly more resources and is in a dedicated
host aggregate within out OpenStack cloud.
=> Move nightly jobs to jenkins.dedicated workers

Jenkinsfile.codenarc, vars/warningsCodeNarc.groovy
CodeNarc doesn't generate a JUnit XML file... So, clearly that original code wasn't going to work :D
Currently this, now correct, code fails due to JENKINS-45930
JENKINS-45930: https://issues.jenkins-ci.org/browse/JENKINS-45930
=> Fix Codenarc Violations reporting

vars/coreKubicProjectCi.groovy, vars/coreKubicProjectPeriodic.groovy, vars/withKubicEnvironment.groovy
Updates the default nodelabels to be slightly more generic, which will also move the PR jobs onto a new larger worker size.
=> Update Jenkins NodeLabels

vars/runK8sE2eTests.groovy
The default time out of 3 hours isn't long enough for some of the e2e tests. This makes it so that if the E2E_WAIT_TIME  env variable is set for the e2e test script then it sets it for the Jenkins timeout as well
=> use E2E_WAIT_TIME to set timeout instead of hard coded value

vars/withKubicEnvironment.groovy
Keep the 'env' output sorted so we can quickly check the status of an
env variable.
=> vars: withKubicEnvironment: Sort 'env' output

vars/withKubicEnvironment.groovy
If domain is not running the 'virsh destroy' command will fail.
This error should simply be ignored since the domain will be undefined
anyway.
=> vars: withKubicEnvironment: Do not fail if domain is not running

vars/coreKubicProjectHousekeeping.groovy
If the job is triggered via regular schedule instead of PR, the
pullRequest object does not exist and it fails as follows:
groovy.lang.MissingPropertyException: No such property: pullRequest for class: coreKubicProjectHousekeeping
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
...
As such, only try to examine that object if we are trully running as
part of a PR.
=> vars: coreKubicProjectHousekeeping: Do not fail if not triggered by PR

vars/withKubicEnvironment.groovy
If domain is not running the 'virsh destroy' command will fail.
This error should simply be ignored since the domain will be undefined
anyway.
(cherry picked from commit 50224d2f624a8ab6a9419a2d754d5f564f436dea)
=> [Backport #243] vars: withKubicEnvironment: Do not fail if domain is not running

vars/runTestK8sConformance.groovy
Add conformance test parameters for the Jenkins pipeline, so it's possible
to choose the sonobuoy repository as well as the container image version.
This allows us to easily choose what version we want to run specifically for
each branch.
(cherry picked from commit c8d23c0)
Backport of https://github.com/kubic-project/jenkins-library/pull/248
=> [3.0] Allow to choose sonobuoy image and version as Jenkins build parameters

vars/coreKubicProjectCi.groovy, vars/withKubicEnvironment.groovy
This is false by default, so all nightly jobs and in general all jobs will
retrieve the supportconfig always (success and failure runs), but for PR
testing it will be faster if we don't retrieve supportconfig for green runs,
giving faster feedback to the user.
Also: Remove mysql result jenkins feeding
We shouldn't be feeding any result accumulator from here, but use other
means instead (like hooks provided by CI).
=> Add support for retrieving supportconfig only on failure

vars/coreKubicProjectHousekeeping.groovy
If the job is triggered via regular schedule instead of PR, the
pullRequest object does not exist and it fails as follows:
groovy.lang.MissingPropertyException: No such property: pullRequest for class: coreKubicProjectHousekeeping
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
...
As such, only try to examine that object if we are trully running as
part of a PR.
(cherry picked from commit c80a5cc58ecdc87db545862fc361932f983de49c)
Backport of https://github.com/kubic-project/jenkins-library/pull/236
=> [3.0] vars: coreKubicProjectHousekeeping: Do not fail if not triggered by PR

vars/coreKubicProjectCi.groovy, vars/withKubicEnvironment.groovy
This is false by default, so all nightly jobs and in general all jobs will
retrieve the supportconfig always (success and failure runs), but for PR
testing it will be faster if we don't retrieve supportconfig for green runs,
giving faster feedback to the user.
(cherry picked from commit 1c1d691dc2f7761d7328295a7549d8294d78881e)
Backport of https://github.com/kubic-project/jenkins-library/pull/255
=> [3.0] Add support for retrieving supportconfig only on failure

vars/createEnvironmentOpenstack.groovy
The stack name was too long leading to failures with the CN field in
the certificates. As such, lets simplify the name a little bit.
=> OpenStack: Simplify the stack name

Jenkinsfile.codenarc
The k8s has been removed from Jenkins master so we should be using
docker directly on the worker.
=> Jenkinsfile.codenarc: Use docker directly

vars/cloneAllKubicRepos.groovy, vars/cloneKubicRepo.groovy, vars/coreKubicProjectCi.groovy, vars/coreKubicProjectPeriodic.groovy, vars/getRepoInfo.groovy, vars/githubCollaboratorCheck.groovy, vars/withKubicEnvironment.groovy
The pipelines assume that everything is hosted on Github. We should instead have a single place to reference all the repository information to make the code more flexible.
=> Do not hardcode repository information in pipelines

vars/cloneKubicRepo.groovy
The repository name is reflected in the project_repo variable so use that when cloning a repository
=> cloneKubicrepo: Use correct variables when cloning repository
